apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "directory-broker.name" . }}-data
  labels:
    {{- include "directory-broker.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
